### ISSUE TITLE
sqlexpress installation

### ISSUE THREAD

**Issue by versofate** [brogersyh/Dockerfiles-for-windows#1]
On windows server 2016TP5 after running docker build -t sqlexpress .

1cf51c47c298: Extracting [==================================================>] 72.03 MB/72.03 MB
849b9bdf7071: Download complete
failed to register layer: convert O:BAG:DUD:(A;OICI;0x1200a9;;;S-1-5-83-0)(A;OICI;FA;;;BA)(A;OICI;FA;;;SY)(A;;FA;;;BA)(A;OICIIO;GA;;;CO)(A;OICI;0x1200a9;;;BU)(A;CI;LC;;;BU)(A;CI;DC;;;BU): The security ID structure is invalid.

**Comment by PatrickLang** [comment]
The first line of the Dockerfile pulls down an existing image:

```
# .NET 3.5 required for SQL Server
FROM docker.io/microsoft/dotnet35:windowsservercore
```

That image has a problem, and will be addressed soon. It's being tracked here:
https://github.com/docker/docker/issues/22404

**Comment by bucrogers** [comment]
resolved as of may 4 when the msft image issue tracked by [docker/docker#22404](https://github.com/docker/docker/issues/22404) was closed
